company_name: 'SANTHOSH FABRICATORS PVT. LTD.'
company_tagline: 'Spl. Fabrication & Erection of Pipe Lines & Structures, Maintenance of W. T. Plants, D. M. Plants & RO-MB Plants.'
company_address: 'PLOT NO 50/19, TIRUPATI PARK, SIKKA, SIKKA JAMNAGAR, Jamnagar, Gujarat, 361141'
company_gstin: 24AAQCS3102E1ZP
company_pan: AAQCS3102E
company_sac: '995442'
company_ra: '10'
default_buyer_name: N/A
default_buyer_address: N/A
default_buyer_gstin: N/A
company_logo:
  - '39'
