_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: 1b8cdf6d-a63c-4dfc-8a53-299a7804ec70
name: frozen
mail: frozen@test.com
slogan: ''
page:
  403: ''
  404: ''
  front: /projects
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
