_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en-gb
uuid: fe718318-157f-4c09-8217-db5e131a365a
name: frozendrops
mail: test@test.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en-gb
mail_notification: null
